---
title: "EDA_California"
output: html_document
date: "2022-11-11"
---

```{r}
library(moments)
library(ggplot2)
library(corrplot)
library(ggpubr)
library(tidyverse)
```


```{r}
#Cargo el dataset
california <- read.csv('california.dat', comment.char = '@', 
                     header = FALSE, stringsAsFactors = TRUE)

dim(california)
str(california)
```

```{r}
names(california) <- c("Longitude", "Latitude", "HousingMedianAge",
                 "TotalRooms", "TotalBedrooms", "Population", "Households",
                 "MedianIncome", "MedianHouseValue")

#Asignacion automatica, facilita el acceso a los campos
#n <- length(names(california)) - 1
#names(california)[1:n] <- paste ("X", 1:n, sep="")
#names(california)[n+1] <- "Y"
```


```{r}
#Missing values
any(is.na(california))

#muestras duplicadas
sum(duplicated(california))
```








```{r}
#Medidad importantes
summary(california)
```

```{r}
desviacion = apply(california, 2, sd)
format(desviacion, scientific = FALSE)
```

```{r}
skev <- apply(california, 2, skewness)
kurt <- apply(california, 2, kurtosis)
format(skev, scientific = FALSE)
format(kurt, scientific = FALSE)
```







Representacion gráfica
```{r}
ggplot(california, aes(y=Longitude)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=Latitude)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=HousingMedianAge)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=TotalRooms)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=TotalBedrooms)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=Population)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=Households)) +
    geom_boxplot(outlier.color = "red")
ggplot(california, aes(y=MedianIncome)) +
    geom_boxplot(outlier.color = "red")

ggplot(california, aes(y=MedianHouseValue)) +
    geom_boxplot(outlier.color = "red")
```

```{r}
ggplot(california, aes(x=Longitude)) +
    geom_histogram()
ggplot(california, aes(x=Latitude)) +
    geom_histogram()
ggplot(california, aes(x=HousingMedianAge)) +
    geom_histogram()
ggplot(california, aes(x=TotalRooms)) +
    geom_histogram()
ggplot(california, aes(x=TotalBedrooms)) +
    geom_histogram()
ggplot(california, aes(x=Population)) +
    geom_histogram()
ggplot(california, aes(x=Households)) +
    geom_histogram()
ggplot(california, aes(x=MedianIncome)) +
    geom_histogram()

ggplot(california, aes(x=MedianHouseValue)) +
    geom_histogram()
```











Truncado en 500000
```{r}

ggplot(california, aes(x = MedianIncome , y= MedianHouseValue)) +
    geom_point()

california_clean <- drop(california[california$MedianHouseValue < 500000, ])
#Para resetear los indices
rownames(california_clean) <- NULL

ggplot(california_clean, aes(x = MedianIncome , y= MedianHouseValue)) +
    geom_point()

```

Outliers
```{r}
ggplot(california_clean, aes(x = TotalRooms  , y = MedianHouseValue, color = TotalRooms > (quantile(TotalRooms, 0.75) + IQR(TotalRooms)*1.5) )) +
    geom_point()  +
  labs(title="Outliers TotalRooms", color="Outliers")

ggplot(california_clean, aes(x = TotalBedrooms  , y = MedianHouseValue, color = TotalBedrooms > (quantile(TotalBedrooms, 0.75) + IQR(TotalBedrooms)*1.5) )) +
    geom_point()  +
  labs(title="Outliers TotalBedrooms", color="Outliers")

ggplot(california_clean, aes(x = Population  , y = MedianHouseValue, color = Population > (quantile(Population, 0.75) + IQR(Population)*1.5) )) +
    geom_point()  +
  labs(title="Outliers Population", color="Outliers")

ggplot(california_clean, aes(x = Households  , y = MedianHouseValue, color = Households > (quantile(Households, 0.75) + IQR(Households)*1.5) )) +
    geom_point()  +
  labs(title="Outliers Households", color="Outliers")

ggplot(california_clean, aes(x = MedianIncome  , y = MedianHouseValue, color = MedianIncome > (quantile(MedianIncome, 0.75) + IQR(MedianIncome)*1.5) )) +
    geom_point()  +
  labs(title="Outliers MedianIncome", color="Outliers")

```
```{r}
out_TotalRooms <- quantile(california_clean$TotalRooms, 0.75) + IQR(california_clean$TotalRooms)*1.5

out_TotalBedrooms <- quantile(california_clean$TotalBedrooms, 0.75) + IQR(california_clean$TotalBedrooms)*1.5

out_Population <- quantile(california_clean$Population, 0.75) + IQR(california_clean$Population)*1.5

out_Households <- quantile(california_clean$Households, 0.75) + IQR(california_clean$Households)*1.5



california_new <- drop(california_clean[california_clean$TotalRooms < out_TotalRooms ,])
california_new <- drop(california_clean[california_clean$TotalBedrooms < out_TotalBedrooms ,])
california_new <- drop(california_clean[california_clean$Population < out_Population ,])
california_new <- drop(california_clean[california_clean$Households < out_Households ,])
#Para resetear los indices
rownames(california_new) <- NULL

#Se eliminan un 2% solamente, interesa
dim(california_new)
```





Matriz de correlaciones
```{r}
corr_matrix <- cor(california_new, method = "kendall")
corrplot(corr_matrix, method = "color", tl.col = "black")
```




```{r}
#Primera hipotesis
ggplot(california_new, aes(x = Longitude, y = Latitude, color = MedianHouseValue, hue = MedianHouseValue))+
  geom_point() +
  labs(title="Valor medio de la vivienda dependiendo de la localizacion", color="MedianHouseValue") +
  scale_color_gradient(low="blue", high="red")
```


```{r}
mapa <- png::readPNG("mapa.png")

ggplot(california_new, aes(x = Longitude, y = Latitude, color = MedianHouseValue, hue = MedianHouseValue))+
  background_image(mapa)+
  geom_point() +
  labs(title="Valor medio de la vivienda dependiendo de la localizacion", color="MedianHouseValue") +
  scale_color_gradient(low="blue", high="red")
  
```


```{r}
#Segunda hipotesis
ggplot(california_new, aes(x = Longitude, y = Latitude, color = MedianHouseValue, size = Population))+
  background_image(mapa)+
  geom_point() +
  labs(title="Valor medio de la vivienda dependiendo de la localizacion", color="MedianHouseValue") +
  scale_color_gradient(low="blue", high="red")
  
```
```{r}
ggplot(california_new, aes(x = Population, y = MedianHouseValue))+
  geom_point() 
```



```{r}
#Hipotesis 3
ggplot(california_new, aes(x = MedianIncome, y = MedianHouseValue))+
  geom_point(color = "blue") 
```


```{r}
#Hipotesis 4
ggplot(california_new, aes(x = HousingMedianAge, y = MedianHouseValue))+
  geom_point(color = "blue") 

ggplot(california_new, aes(x = Longitude, y = Latitude, color = HousingMedianAge))+
  background_image(mapa)+
  geom_point() +
  labs(title="Edad media de la vivienda dependiendo de la localizacion", color="HousingMedianAge") +
  scale_color_gradient(low="green", high="purple")
```
Poner los dos juntos en latex para comparar 
```{r}
ggplot(california_new, aes(x = Longitude, y = Latitude, color = MedianHouseValue, hue = MedianHouseValue))+
  background_image(mapa)+
  geom_point() +
  labs(title="Valor medio de la vivienda dependiendo de la localizacion", color="MedianHouseValue") +
  scale_color_gradient(low="blue", high="red")
```

