---
title: "EDA_bupa"
output: html_document
date: "2022-11-12"
---

```{r}
library(moments)
library(ggplot2)
library(tidyverse)
```


```{r}
#Cargo el dataset
bupa <- read.csv('bupa.dat', comment.char = '@', 
                     header = FALSE, stringsAsFactors = TRUE)

dim(bupa)
str(bupa)
```
```{r}
names(bupa) <- c("mcv", "alkphos", "sgpt",
                 "sgot", "gammagt", "drinks", "selector")
```






```{r}
#Missing values
any(is.na(bupa))

#muestras duplicadas
sum(duplicated(bupa))

bupa <- bupa[!duplicated(bupa), ]
dim(bupa)

#Para resetear los indices
rownames(bupa) <- NULL
```



```{r}
#Medidadas importantes
summary(bupa)
```


```{r}
desviacion = apply(bupa, 2, sd)
format(desviacion, scientific = FALSE)
```

```{r}
skev <- apply(bupa, 2, skewness)
kurt <- apply(bupa, 2, kurtosis)
format(skev, scientific = FALSE)
format(kurt, scientific = FALSE)
```



Representacion gráfica
```{r}
ggplot(bupa, aes(y=mcv)) +
    geom_boxplot(outlier.color = "red")
ggplot(bupa, aes(y=alkphos)) +
    geom_boxplot(outlier.color = "red")
ggplot(bupa, aes(y=sgpt)) +
    geom_boxplot(outlier.color = "red")
ggplot(bupa, aes(y=sgot)) +
    geom_boxplot(outlier.color = "red")
ggplot(bupa, aes(y=gammagt)) +
    geom_boxplot(outlier.color = "red")


ggplot(bupa, aes(y=drinks)) +
    geom_boxplot(outlier.color = "red")
```


```{r}
ggplot(bupa, aes(x=mcv)) +
    geom_histogram()
ggplot(bupa, aes(x=alkphos)) +
    geom_histogram()
ggplot(bupa, aes(x=sgpt)) +
    geom_histogram()
ggplot(bupa, aes(x=sgot)) +
    geom_histogram()
ggplot(bupa, aes(x=gammagt)) +
    geom_histogram()


ggplot(bupa, aes(x=drinks)) +
    geom_histogram(bins = 5)
```




```{r}
shapiro.test(sample(bupa[ , 'mcv']))
shapiro.test(sample(bupa[ , 'alkphos']))
shapiro.test(sample(bupa[ , 'sgpt']))
shapiro.test(sample(bupa[ , 'sgot']))
shapiro.test(sample(bupa[ , 'gammagt']))
```














Outliers izquierda
```{r}
ggplot(bupa, aes(x = mcv  , y = drinks, color = mcv < (quantile(mcv, 0.25) - IQR(mcv)*1.5) )) +
    geom_point()  +
  labs(title="Outliers mcv", color="Outliers")


ggplot(bupa, aes(x = sgot  , y = drinks, color = sgot < (quantile(sgot, 0.25) - IQR(sgot)*1.5) )) +
    geom_point()  +
  labs(title="Outliers sgot", color="Outliers")


```
```{r}
bupa[which(bupa$mcv < (quantile(bupa$mcv, 0.25) - IQR(bupa$mcv)*1.5)),]
bupa[which(bupa$sgot < (quantile(bupa$sgot, 0.25) - IQR(bupa$sgot)*1.5)),]
```



Outliers derecha
```{r}
ggplot(bupa, aes(x = mcv  , y = drinks, color = mcv > (quantile(mcv, 0.75) + IQR(mcv)*1.5) )) +
    geom_point()  +
  labs(title="Outliers mcv", color="Outliers")

ggplot(bupa, aes(x = alkphos  , y = drinks, color = alkphos > (quantile(alkphos, 0.75) + IQR(alkphos)*1.5) )) +
    geom_point()  +
  labs(title="Outliers alkphos", color="Outliers")

ggplot(bupa, aes(x = sgpt  , y = drinks, color = sgpt > (quantile(sgpt, 0.75) + IQR(sgpt)*1.5) )) +
    geom_point()  +
  labs(title="Outliers sgpt", color="Outliers")

ggplot(bupa, aes(x = sgot  , y = drinks, color = sgot > (quantile(sgot, 0.75) + IQR(sgot)*1.5) )) +
    geom_point()  +
  labs(title="Outliers sgot", color="Outliers")

ggplot(bupa, aes(x = gammagt  , y = drinks, color = gammagt > (quantile(gammagt, 0.75) + IQR(gammagt)*1.5) )) +
    geom_point()  +
  labs(title="Outliers gammagt", color="Outliers")

```



#Preparo la variable dependiente
```{r}
unique(bupa$drinks)
```


```{r}
bupa$drinks[bupa$drinks <= 5] <- 0
bupa$drinks[bupa$drinks > 5] <- 1

summary(bupa)
```

```{r}
#Separo según la variable selector
bupa_train <- bupa %>% filter(selector == 2)
bupa_test <- bupa %>% filter(selector == 1)
```

```{r}
dim(bupa_train)
dim(bupa_test)
```
```{r}
bupa_train %>% count(drinks)
bupa_test %>% count(drinks)
```









```{r}
no_label_bupa <- bupa %>% select(c(-drinks, -selector))
```


Matriz de correlaciones
```{r}
corr_matrix <- cor(no_label_bupa, method = "kendall")
corrplot(corr_matrix, method = "num", tl.col = "black")
```





```{r}
pairs(bupa)
```
```{r}
#Hipotesis 1
ggplot(bupa, aes(x = alkphos, y = mcv, color = drinks))+
  geom_point() 

ggplot(bupa, aes(x = sgpt, y = mcv, color = drinks))+
  geom_point() 

ggplot(bupa, aes(x = sgot, y = mcv, color = drinks))+
  geom_point() 

ggplot(bupa, aes(x = gammagt, y = mcv, color = drinks))+
  geom_point() 
```



```{r}
#hipotesis 2
ggplot(bupa, aes(x = alkphos, y = sgpt))+
  geom_point() 

ggplot(bupa, aes(x = alkphos, y = sgot))+
  geom_point() 

ggplot(bupa, aes(x = alkphos, y = gammagt))+
  geom_point() 


ggplot(bupa, aes(x = sgpt, y = sgot))+
  geom_point() 

ggplot(bupa, aes(x = sgpt, y = gammagt))+
  geom_point() 


ggplot(bupa, aes(x = sgot, y = gammagt))+
  geom_point() 
```


```{r}
ggplot(bupa, aes(x = sgot))+
  geom_histogram() +
  facet_wrap( ~ drinks)
```

